import type { PostWithMeta } from './types';
import { getGalleryImageUrl } from '@/lib/gallery';

export type SampleCategory = 'works' | 'daily' | 'collections' | 'likes';

export interface SamplePost extends PostWithMeta {
  category: SampleCategory;
}

const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

export const SAMPLE_POSTS: SamplePost[] = [
  {
    id: 'sample-1',
    author_id: 'mate-1',
    image_url: getGalleryImageUrl('matcha.jpg'),
    content: '晨雾里的抹茶色调，像一块被时间浸润过的织物。纤维的纹理在柔光下若隐若现。',
    tags: ['纤维艺术', '自然主义'],
    status: 'published',
    created_at: daysAgo(1),
    author: {
      id: 'mate-1',
      username: '林知夏',
      avatar_url: getGalleryImageUrl('light-gray.png'),
      role: 'user',
      created_at: daysAgo(90),
    },
    likes_count: 128,
    comments_count: 24,
    is_liked_by_me: false,
    category: 'works',
  },
  {
    id: 'sample-2',
    author_id: 'mate-2',
    image_url: getGalleryImageUrl('light-pink.jpg'),
    content: '粉彩瓷上的纹样，是手与泥土对话留下的痕迹。每一笔都不追求对称，却自有韵律。',
    tags: ['粉彩瓷纹样', '手工艺'],
    status: 'published',
    created_at: daysAgo(2),
    author: {
      id: 'mate-2',
      username: '陈墨白',
      avatar_url: getGalleryImageUrl('dark-light-gray.png'),
      role: 'user',
      created_at: daysAgo(120),
    },
    likes_count: 96,
    comments_count: 18,
    is_liked_by_me: true,
    category: 'works',
  },
  {
    id: 'sample-3',
    author_id: 'mate-3',
    image_url: getGalleryImageUrl('cyberpunk-1.png'),
    content: '霓虹与雾面材质的碰撞，抽象构成里藏着城市夜晚的温度。',
    tags: ['现代抽象', '赛博朋克'],
    status: 'published',
    created_at: daysAgo(3),
    author: {
      id: 'mate-3',
      username: '苏晚棠',
      avatar_url: getGalleryImageUrl('cyberpunk-2.png'),
      role: 'user',
      created_at: daysAgo(60),
    },
    likes_count: 74,
    comments_count: 12,
    is_liked_by_me: false,
    category: 'daily',
  },
  {
    id: 'sample-4',
    author_id: 'mate-1',
    image_url: getGalleryImageUrl('sea-salt.png'),
    content: '今日工作台一角。海盐色系的三件小物，构成了我的极简日常。',
    tags: ['纤维艺术', '极简'],
    status: 'published',
    created_at: daysAgo(4),
    author: {
      id: 'mate-1',
      username: '林知夏',
      avatar_url: getGalleryImageUrl('light-gray.png'),
      role: 'user',
      created_at: daysAgo(90),
    },
    likes_count: 52,
    comments_count: 8,
    is_liked_by_me: false,
    category: 'daily',
  },
  {
    id: 'sample-5',
    author_id: 'mate-4',
    image_url: getGalleryImageUrl('oat.png'),
    content: '「燕麦」主题策展片段——温暖中性色如何塑造空间的呼吸感。',
    tags: ['粉彩瓷纹样', '策展'],
    status: 'published',
    created_at: daysAgo(5),
    author: {
      id: 'mate-4',
      username: '顾清和',
      avatar_url: getGalleryImageUrl('matcha.jpg'),
      role: 'user',
      created_at: daysAgo(200),
    },
    likes_count: 201,
    comments_count: 36,
    is_liked_by_me: true,
    category: 'collections',
  },
  {
    id: 'sample-6',
    author_id: 'mate-2',
    image_url: getGalleryImageUrl('dark-pink.jpg'),
    content: '黑与粉的边界实验。两种极端色彩在构图中找到微妙的共存方式。',
    tags: ['现代抽象', '纤维艺术'],
    status: 'published',
    created_at: daysAgo(6),
    author: {
      id: 'mate-2',
      username: '陈墨白',
      avatar_url: getGalleryImageUrl('dark-light-gray.png'),
      role: 'user',
      created_at: daysAgo(120),
    },
    likes_count: 88,
    comments_count: 15,
    is_liked_by_me: false,
    category: 'collections',
  },
  {
    id: 'sample-7',
    author_id: 'mate-3',
    image_url: getGalleryImageUrl('cyberpunk-2.png'),
    content: '喜欢清单 · 第 03 期：收集一切关于「未来复古」的视觉碎片。',
    tags: ['赛博朋克', '视觉收集'],
    status: 'published',
    created_at: daysAgo(7),
    author: {
      id: 'mate-3',
      username: '苏晚棠',
      avatar_url: getGalleryImageUrl('cyberpunk-2.png'),
      role: 'user',
      created_at: daysAgo(60),
    },
    likes_count: 143,
    comments_count: 21,
    is_liked_by_me: true,
    category: 'likes',
  },
  {
    id: 'sample-8',
    author_id: 'mate-4',
    image_url: getGalleryImageUrl('dark-light-gray.png'),
    content: '灰阶里的层次，比任何高饱和色彩都更难驾驭，也更有力量。',
    tags: ['极简', '构成'],
    status: 'published',
    created_at: daysAgo(8),
    author: {
      id: 'mate-4',
      username: '顾清和',
      avatar_url: getGalleryImageUrl('matcha.jpg'),
      role: 'user',
      created_at: daysAgo(200),
    },
    likes_count: 67,
    comments_count: 9,
    is_liked_by_me: true,
    category: 'likes',
  },
];

export function isSamplePostId(id: string): boolean {
  return id.startsWith('sample-');
}
